#ifndef __CONST_H__
#define __CONST_H__

#define DEFAULT_BLOCK_SIZE 8
#define DEFAULT_NUM_BLOCKS 4
#define MAX_BLOCK_SIZE 32
#define MAX_NUM_BLOCKS 32
#define MASTER_INSTANCE_ID 0
#define MESSAGE_TAG_BLOCK_READ_REQUEST 100
#define MESSAGE_TAG_BLOCK_READ_RESPONSE 101
#define MESSAGE_TAG_BLOCK_WRITE_REQUEST 102
#define MESSAGE_TAG_BLOCK_UPDATE_NOTIFICATION 103
#define OPERATION_SLEEP_INTERVAL_MILLIS 10000

#endif
